mamba1_denoiser:
  target: mamba_attn_diff.models.architectures.motion_mamba1_denoiser.MotionMambaDenoiser
  params:
    text_encoded_dim: 768
    ff_size: 1024
    num_layers: 11
    num_heads: 4
    dropout: 0.1
    normalize_before: False
    activation: 'gelu'
    flip_sin_to_cos: True
    return_intermediate_dec: False
    position_embedding: 'learned'
    arch: trans_enc
    freq_shift: 0
    condition: ${model.condition}
    latent_dim: ${model.latent_dim}
    guidance_scale: ${model.guidance_scale}
    guidance_uncondp: ${model.guidance_uncondp}
    nfeats: ${DATASET.NFEATS}
    nclasses: ${DATASET.NCLASSES}
    ablation: ${TRAIN.ABLATION}
    d_temporal: ${model.latent_dim[0]}
    d_state: ${model.d_state}
    d_conv: ${model.d_conv}
    d_model: ${model.latent_dim[1]}
    expand: ${model.expand}
    dt_rank: "auto"
    dt_min: 0.001
    dt_max: 0.1
    dt_init: "random"
    dt_scale: 1.0
    dt_init_floor: 1e-4
    drop_rate: 0.
    norm_epsilon: 1e-5 
    rms_norm: True 
    residual_in_fp32: True
    conv_bias: True
    bias: False
    use_fast_path: True  # Fused kernel options
    layer_idx: None
    device: {ACCELERATOR}
    dtype: fp32
    log: False
    version: v2