####################################
# The following are general settings
####################################

# Experiment name, more details in Section 'Experiment Name Explanation'
# NAME: 1222_PELearn_Diff_Latent1_MEncDec49_MdiffEnc49_bs64_clip_uncond75_01
# NAME: MotionGenAI_Given_MLD_Test
NAME: The First Motion Mamba Test
# Debug mode. Set to True will enter the debug mode, then the program will
# 1. use a tiny dataset for trianing and evaluation
# 2. validate more intensively
# 3. will not use `wandb logger`
DEBUG: False
# Devices. Optional: “cpu”, “gpu”
ACCELERATOR: 'gpu'
# Index of GPUs eg. [0] or [0,1,2,3]
DEVICE: [0]

#####################################
# The following are training settings
#####################################
TRAIN:
  # Model stage. Optional: "vae", "diffusion"
  STAGE: diffusion
  # Training dataset name
  DATASETS: ['humanml3d']
  # Number of dataloader workers
  NUM_WORKERS: 8
  # Size of batches
  BATCH_SIZE: 128
  # Total epochs for training
  END_EPOCH: 3000

  RESUME: '' # Resume training from this path
  PRETRAINED_VAE: './checkpoints/mld_humanml3d_checkpoint/1222_mld_humanml3d_FID041.ckpt' # vae model path
  OPTIM:
    TYPE: AdamW # Optimizer type
    LR: 1e-4 # Learning rate
  # Ablation study configurations.
  ABLATION:
    SKIP_CONNECT: True
    PE_TYPE: mld
    DIFF_PE_TYPE: mld

#####################################
# The following are validation settings
#####################################
EVAL:
  DATASETS: ['humanml3d'] # Evaluating datasets
  BATCH_SIZE: 32 # Evaluating Batch size
  ##### Evaluation 여기 바꿨다 승환아 잊지마라 eval이상하면 여기가 문제다
  SPLIT: test

#####################################
# The following are testing settings
#####################################
TEST:
  CHECKPOINTS: ./checkpoints/mld_humanml3d_checkpoint/1222_mld_humanml3d_FID041.ckpt # Pretrained model path
  DATASETS: ['humanml3d'] # training datasets
  SPLIT: test
  BATCH_SIZE: 1 # training Batch size
  MEAN: False
  NUM_SAMPLES: 1
  REPLICATION_TIMES: 1
  FACT: 1

#####################################
# The following are basic datasets settings
#####################################
DATASET:
  JOINT_TYPE: 'humanml3d' # join type

#####################################
# The following are metric settings
#####################################
METRIC:
  TYPE: ['TemosMetric', 'TM2TMetrics']

#####################################
# The following are training losses settings
#####################################
LOSS:
  TYPE: mld # Losses type
  LAMBDA_LATENT: 1.0e-5 # Lambda for latent Losses
  LAMBDA_KL: 1.0e-4 # Lambda for kl Losses
  LAMBDA_REC: 1.0 # Lambda for reconstruction Losses
  LAMBDA_GEN: 1.0 # Lambda for text-motion generation losses
  LAMBDA_CROSS: 1.0 # Lambda for reconstruction Losses
  LAMBDA_CYCLE: 0.0 # Lambda for cycle Losses
  LAMBDA_PRIOR: 0.0
  DIST_SYNC_ON_STEP: False # Sync Losses on step when distributed trained

#####################################
# The following are basic model settings
#####################################
model:
  vae: true # whether vae model
  model_type: mm1 # model type
  condition: 'text'
  latent_dim: [1, 256] # latent dimension
  d_temporal: 1 # latent_dim[0]
  d_state: 16 # SSM state expansion factor
  d_conv: 4   # Local convolution width
  num_layers: 11 # number of layers
  expand: 2    # Block expansion factor
  num_head: 4 # number of head layers
  droupout: 0.1 # dropout rate
  activation: gelu # activation type
  guidance_scale: 7.5 #
  guidance_uncondp: 0.1 # 0.1 0.25

#####################################
# The following are loggers settings
#####################################
# Logger configuration
LOGGER:
  SACE_CHECKPOINT_EPOCH: 100
  LOG_EVERY_STEPS: 1
  VAL_EVERY_STEPS: 50
  TENSORBOARD: False
  WANDB:
    PROJECT: null
    # PROJECT: 'Motion-Latent-Diffusion/MLD'
    OFFLINE: False
    RESUME_ID: 'VAE'
  NEPTUNE:
    PROJECT: 'Motion-Latent-Diffusion/MotionMamba'
    API_KEY: ./api_key.txt
    RESUME_ID: 'VAE'